version: '4'
services:
  app:
    image: app:latest
    container_name: app
    restart: always
    ports:
      - 3000:3000
    networks:
      - no-top-api
    volumes:
      - ./.env:/opt/app/.env
networks:
  no-top-api:
    external: true
